name: Release

on:
  push:
    tags:
    - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ github.ref }}" | sed 's|refs/tags/v||' | (read h; echo "image_version=${h}") >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: blbrdv/simple-quote-bot:latest,blbrdv/simple-quote-bot:${{ env.image_version }}
          cache-from: type=registry,ref=blbrdv/simple-quote-bot:latest
          cache-to: type=inline

      - name: Release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /SimpleQuoteBot 
            git pull
            docker-compose pull
            docker-compose up -d
