name: Release

on:
  push:
    tags:
    - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ github.ref }}" | sed 's|refs/tags/v||' | (read h; echo "image_version=${h}") >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: blbrdv/simple-quote-bot:latest,blbrdv/simple-quote-bot:${{ env.image_version }}
          cache-from: type=registry,ref=blbrdv/simple-quote-bot:latest
          cache-to: type=inline

      # - name: Stop
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: cd /SimpleQuoteBot && docker compose down
      #     host: ${{ secrets.SERVER_IP }}
      #     passphrase: ${{ secrets.SERVER_PASSPHRASE }}
      #     privateKey: ${{ secrets.SERVER_PRIVATE_KEY}}

      - name: Stop
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd /SimpleQuoteBot && docker compose down

      - name: Release
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "docker-compose.yaml"
          target: /SimpleQuoteBot
      
      
      # - name: Run
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: cd /SimpleQuoteBot && docker compose up -d
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     passphrase: ${{ secrets.SERVER_PASSPHRASE }}
      #     privateKey: ${{ secrets.SERVER_PRIVATE_KEY}}

      - name: Run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd /SimpleQuoteBot && docker compose up -d
      
      - name: Github release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
